trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  displayName: "Setup"  
  inputs:
    versionSource: 'spec'
    versionSpec: '20.x'

- script: 'npm install'
  displayName: "Instala depêndencias"
- script: 'npm run cy:run-junit'
  displayName: "Executa os testes"
- task: PublishTestResults@2
  displayName: "Gera o Relatório"
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/*.xml'